### ISSUE TITLE
On arte TV, problem with the audio language

### ISSUE THREAD

**Issue by Philetjosie** [NickvisionApps/Parabolic#752] opened 2024-03-19 17:22 UTC
On Arte TV, there are multiple choices of audio language. For example, for this movie: https://www.arte.tv/fr/videos/113517-000-A/les-passagers-de-la-nuit/  the choices are: French, German, French with audiodescription, German with audiodescription.

However, on Parabole, I only get 2 choices: French or German.  And worse, when I choose French, the audio I really get is French with audiodescription, which makes the movie almost unwatchable !!

It would be great that Parabole offers the 4 choices, or at least, that the FR choice is the real French, and not the one with audiodescription.

I must add that I have had this problem at least for 3 or 4 movies on arte tv, that I recorded, but I realised the problem too late, the movie was no more available.
Best regards, and thanks again for your great Sofware !

**Comment by nlogozzo** [comment] 2024-05-15 19:15
This depends on how yt-dlp tells Parabolic about the languages available. 

I will look into it.

**Comment by nlogozzo** [comment] 2024-08-08 03:08
It seems that the link you provided is no longer available.

Do you have a more recent URL for me to test?

**Comment by Philetjosie** [comment] 2024-08-18 09:46
Hello, I tried today with: https://www.arte.tv/fr/videos/118127-000-A/nous-irons-tous-au-paradis/

With yt-dlp, I have clear indication that there is a french audio and a french with audiodescription:
philippe@philippe-desktop:~$ /usr/local/bin/yt-dlp -F https://www.arte.tv/fr/videos/118127-000-A/nous-irons-tous-au-paradis/
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/118127-000-A/nous-irons-tous-au-paradis/
[ArteTV] 118127-000-A: Downloading JSON metadata
[ArteTV] 118127-000-A: Downloading m3u8 information
[info] Available formats for 118127-000-A:
ID                                      EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
VOF-audio_0-Allemand                    mp4 audio only     │                  m3u8  │ audio only        unknown    [de] Français [VOF]
VOF-audio_0-Français                    mp4 audio only     │                  m3u8  │ audio only        unknown    [fr] Français [VOF]
VOF-audio_0-Français__audiodescription_ mp4 audio only     │                  m3u8  │ audio only        unknown    [fr] Français [VOF]

However, If I choose FR langage in Parabole, I get the french with audiodescription, and not the correct one. May be Parabole should propose both French soundtracks, and give the choice between them ?

Thanks and best regards.

**Comment by nlogozzo** [comment] 2024-09-04 14:00
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)

**Comment by Philetjosie** [comment] 2024-09-04 17:20
Hello, I just did a test, and unfortunately, I still have the problem with the french language on Arte.tv. I select French in Parabolic (there is only FR or DE as choice, but on Arte.tv there is 3 choices, FR, DE, and FR with Audiodescription), but I get the French with Audiodescription instead of French. I made the latest test with this movie: https://www.arte.tv/fr/videos/031918-000-A/melodie-en-sous-sol/

**Comment by nlogozzo** [comment] 2024-09-04 18:16
The problem is `yt-dlp` displays both `fr` and `fr with audiodescription` as `"language": "fr"`...so there's no real easy way to distinguish between them...

I have to see If I can come up with something...

**Comment by nlogozzo** [comment] 2024-09-04 20:44
![image](https://github.com/user-attachments/assets/1b9572a4-7b48-43e9-92c1-bfc7bee80258)

**Closed** 2024-09-04 20:58 UTC
Labels: bug

**Comment by nlogozzo** [comment] 2024-09-04 21:35
You can download and test the gnome flatpak file from this build: https://github.com/NickvisionApps/Parabolic/actions/runs/10709401101

Once you download and extract the zip file you can run the following commands:
```
flatpak install org.nickvision.tubeconverter.gnome.flatpak
flatpak run org.nickvision.tubeconverter//master
```
and once you are done testing:
```
flatpak uninstall org.nickvision.tubeconverter//master
```

**Comment by nlogozzo** [comment] 2024-09-05 01:20
Parabolic [V2024.9.0-beta2](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta2) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)

**Comment by Philetjosie** [comment] 2024-09-05 09:01
Hello, I tried beta2, and it is working perfectly. That's great, many thanks ! And also, it will allow peoples who needs the audiodescription to have the choice to get it, so it is also a good thing for better inclusion !
Many thanks again !

**Comment by nlogozzo** [comment] 2024-09-05 09:31
Happy to hear :)
