### ISSUE TITLE
It's not possible to download

### ISSUE THREAD

**Issue by Francehelder** [NickvisionApps/Parabolic#849] opened 2024-10-03 03:08 UTC
Parabolic freeze after clicking to download

I'm using the latest version: 2024.10.0. I reinstalled it, but didn't work!

SO: Endeavour OS
Kernel: 6.6.52-1-lts

**Comment by Francehelder** [comment] 2024-10-03 21:32
Yes, i'm using the Flatpak version.

Didn't work with every URL i tried. For example: https://www.reddit.com/r/tropadocalvo/comments/1fto8s3/setembro_amarelo_acabou_ontem/

I'm using the default options.

![image](https://github.com/user-attachments/assets/0c9a15dd-665a-4440-88f3-dfc7f1639c79)

**Comment by sinthesizer** [comment] 2024-10-04 01:56
I'm having the same problem sort of.  I can download using default settings(using yt-dlp) but when I add aria2 in preferences and hit the download button the app freezes. I didn't have this problem before the update, everything worked fine with aria2 chosen. I'm using the flatpak version. I'm running Linux Mint 22 also.

**Comment by nlogozzo** [comment] 2024-10-04 12:05
> I'm having the same problem sort of. I can download using default settings(using yt-dlp) but when I add aria2 in preferences and hit the download button the app freezes. I didn't have this problem before the update, everything worked fine with aria2 chosen. I'm using the flatpak version. I'm running Linux Mint 22 also.

This is a separate issue you are having see #860

**Comment by Francehelder** [comment] 2024-10-05 18:05
aria2c was enabled.
After disable it, download works.

**Comment by nlogozzo** [comment] 2024-10-05 18:07
Yeah okay so then marking as a duplicate of #860 .

Will be fixed in the next update.

**Closed by nlogozzo** 2024-10-05 18:07 UTC
Labels: bug, waiting-for-author
