### ISSUE TITLE
Couldn't add any downloading

### ISSUE THREAD

**Issue by NotMephisto** [NickvisionApps/Parabolic#886] opened 2024-10-12 18:07 UTC
![image](https://github.com/user-attachments/assets/56bde21c-af65-4856-b11a-c9b32c0cdbc0)

Button's not clickable 

OS: Fedora 40
Package: Flatpak
DE: Hyprland

**Comment by nlogozzo** [comment] 2024-10-12 18:10
Duplicate of other issues.

A fix is in main and will be released soon!

**Closed by nlogozzo** 2024-10-12 18:10 UTC
