### ISSUE TITLE
High CPU usage and unresponsiveness when downloading

### ISSUE THREAD

**Issue by rassoc** [NickvisionApps/Parabolic#432] opened 2023-07-03 22:52 UTC
Platform: i5, Gnome 44, Wayland, openSUSE Tumbleweed, Flatpak v2023.7.0

I'm seeing high CPU usage according to htop (around 116%) for the flatpak app whenever it is downloading. Even with just a single download stream from twitch. 
The CPU usage drops whenever the download slows down or halts for a second, but rises when the download speed picks up again. Using yt-dlp on the terminal for the same file yields almost no CPU usage. 
Also, if the stream is rather long, 10h or so, the whole window becomes unresponsive and requires force-quitting before the download is complete.
Yt-dlp seems to be producing quite a bit of log entries, updating the progress indicator multiple times per second. Could log spam be the issue?

**Comment by nlogozzo** [comment] 2023-07-04 05:36
Sounds like #402 again...I thought I fixed the log issues, clearing them from memory as the download progresses...

What version of the app are you using?

As a work around you can turn on using aria2c downloader in Preferences and the issue should be fixed (since aria2 doesn't produce any logs)

@fsobolev thoughts?

**Comment by rassoc** [comment] 2023-07-04 08:55
> What version of the app are you using?

 2023.7.0, latest flatpak from 3 days ago.

> Sounds like #402 again

Not sure, only seeing around 300mb mem usage on a regular run. But I got a coredump once when the app refused to close after freezing up and that one ate up 32gb of ram before it got killed by the OOMK.

**Comment by fsobolev** [comment] 2023-07-04 11:45
> @fsobolev thoughts?

I can reproduce it, will look what I can do.

**Comment by nlogozzo** [comment] 2023-07-04 11:58
> I can reproduce it (up to 30% CPU usage when downloading, normally it's ~2%), will look what I can do.

It's definitely because of the logs. And like I said i fixed it a little because i forgot to call Dispose on the DownloadProgressState...but looks like the logs are just too large to store.

The problem is we make a new string every time, which takes allocations obviously. But we can to make new logs cause we read from a file.

**Closed** 2023-07-04 18:02 UTC
Labels: bug
