### ISSUE TITLE
Some utf8 shows bad

### ISSUE THREAD

**Issue by LogoJorge** [NickvisionApps/Parabolic#861] opened 2024-10-04 03:11 UTC
Add Files in spanish is Añadir Descarga shows A~nadir Descarga

All UTF8 characters not show correctly in windows 10 

ñ ~n
Ñ ~N
á
Á
í  'i
etc.etc

**Comment by nlogozzo** [comment] 2024-10-04 12:01
Duplicate of #845

**Closed by nlogozzo** 2024-10-04 12:01 UTC
