### ISSUE TITLE
Bad hungarian character displaying.

### ISSUE THREAD

**Issue by McKangi** [NickvisionApps/Parabolic#916] opened 2024-10-23 09:30 UTC
The Hungarian language is displayed incorrectly. The accents of specific Hungarian characters are not displayed above the letter, but before the letter, as a separate character. oh -> 'o he ->"o é -> 'e   version: 2024.10.02

![Képernyőkép 2024-10-23 112527](https://github.com/user-attachments/assets/46efce23-15f9-4723-8387-5d3339c318d3)

**Comment by nlogozzo** [comment] 2024-10-23 10:02
Duplicate of #845. Will be fixed in the next release.

**Closed by nlogozzo** 2024-10-23 10:02 UTC
