### ISSUE TITLE
Crashing in latest version 2024.10.2

### ISSUE THREAD

**Issue by Lolguy8321** [NickvisionApps/Parabolic#911] opened 2024-10-19 14:19 UTC
using the latest version of parabolic 2024.10.2 
some links dont really download and lead to a crash
searched a bit on the issues and others have had this too and it seems like parabolic 2024.9.0-beta1 downloads those same links np
only problem with that version is that when u stop all downloads it ..
c r a s h e s lol

https://www.youtube.com/@SilversCastle/videos
https://www.youtube.com/@SilversCastle/releases
https://www.youtube.com/@SilversCastle/playlists
all three of these crash in the latest version
but in the old beta release they download fine

https://www.youtube.com/@badnukemusic/videos 
https://www.youtube.com/@badnukemusic/playlists

these work in both versions
no idea whats goin on

i didnt change anything pretty much default setting for both of the versions of parabolic
oh and for the 10.2 version i tried both the portable and the installer versions none worked

OS - Windows 10 22h2 19045. 4598

**Comment by nlogozzo** [comment] 2024-10-20 15:49
This is a duplicate of #907.

Will be fixed with 2024.10.3 that I hope to get out tonight!

**Closed by nlogozzo** 2024-10-20 15:49 UTC
