### ISSUE TITLE
[ISSUE - UNSOLVED] This application requires the Windows App Runtime Version (MSIX package version > - 4000.1049.117.0)

### ISSUE THREAD

**Issue by MaiderGoku** [NickvisionApps/Parabolic#759] opened 2024-04-07 15:51 UTC
![Screenshot 2024-04-07 211757](https://github.com/NickvisionApps/Parabolic/assets/105241930/2b3d65b8-f151-42c6-b794-f8873e020273)

Downloaded the latest release 1.5.1 , 1.4.5 and 1.4.3. Yet still the same issue.

**Comment by MaiderGoku** [comment] 2024-04-07 16:11
![Screenshot 2024-04-07 212947](https://github.com/NickvisionApps/Parabolic/assets/105241930/5a7faa29-df36-4dcf-8170-c2c153e9d129)
![Screenshot 2024-04-07 213856](https://github.com/NickvisionApps/Parabolic/assets/105241930/a66255a9-4e02-45ce-bc5f-13fb67595581)
![Screenshot 2024-04-07 213236](https://github.com/NickvisionApps/Parabolic/assets/105241930/867f2dae-34fd-48b2-9263-104084ff64f2)
![Screenshot 2024-04-07 213156](https://github.com/NickvisionApps/Parabolic/assets/105241930/636aab4c-a7d1-4afa-a880-2288b613246e)
![Screenshot 2024-04-07 213104](https://github.com/NickvisionApps/Parabolic/assets/105241930/ee0b2846-de76-46dc-b0be-dc513873b076)

**Comment by playaz44** [comment] 2024-04-10 09:46
Duplicate of [#755](https://github.com/NickvisionApps/Parabolic/issues/755)

**Closed** 2024-04-10 10:53 UTC
